import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import { AgeGroup, Answer, IncidentState, Scenario, createIncident, getScenarioCopy, reduceIncident } from '../src/emergency-state.js';

function answerFlow(...answers){ let s=createIncident('2026-09-05T00:00:00Z'); for(const a of answers)s=reduceIncident(s,{type:'ANSWER',answer:a}); return s; }

test('scene unsafe immediately gives safety guidance',()=>{const s=answerFlow(Answer.NO);assert.equal(s.state,IncidentState.GUIDANCE);assert.equal(s.scenario,Scenario.SCENE_UNSAFE);});
test('unresponsive and not breathing routes directly to adult CPR on construction profile',()=>{const s=answerFlow(Answer.YES,Answer.NO,Answer.NO);assert.equal(s.state,IncidentState.GUIDANCE);assert.equal(s.scenario,Scenario.CPR);assert.equal(s.ageGroup,AgeGroup.ADULT);});
test('unresponsive but breathing routes to unconscious-breathing guidance',()=>{const s=answerFlow(Answer.YES,Answer.NO,Answer.YES);assert.equal(s.scenario,Scenario.UNCONSCIOUS_BREATHING);assert.equal(s.state,IncidentState.GUIDANCE);});
test('responsive severe bleeding routes directly to bleeding control',()=>{const s=answerFlow(Answer.YES,Answer.YES,Answer.YES);assert.equal(s.scenario,Scenario.SEVERE_BLEEDING);assert.equal(s.state,IncidentState.GUIDANCE);});
test('responsive without severe bleeding opens scenario picker',()=>{const s=answerFlow(Answer.YES,Answer.YES,Answer.NO);assert.equal(s.state,IncidentState.SCENARIO_PICKER);});
test('construction profile routes CPR directly to adult while paediatric data remains hidden fallback',()=>{let s=answerFlow(Answer.YES,Answer.YES,Answer.NO);s=reduceIncident(s,{type:'SELECT_SCENARIO',scenario:Scenario.CPR});assert.equal(s.state,IncidentState.GUIDANCE);assert.equal(s.ageGroup,AgeGroup.ADULT);assert.match(getScenarioCopy(Scenario.CPR,AgeGroup.ADULT).steps.join(' '),/5–6 cm/);assert.ok(getScenarioCopy(Scenario.CPR,AgeGroup.CHILD));assert.ok(getScenarioCopy(Scenario.CPR,AgeGroup.INFANT));});
test('construction profile routes choking directly to adult while paediatric data remains hidden fallback',()=>{let s=answerFlow(Answer.YES,Answer.YES,Answer.NO);s=reduceIncident(s,{type:'SELECT_SCENARIO',scenario:Scenario.CHOKING});assert.equal(s.state,IncidentState.GUIDANCE);assert.equal(s.ageGroup,AgeGroup.ADULT);assert.match(getScenarioCopy(Scenario.CHOKING,AgeGroup.ADULT).steps.join(' '),/abdominal thrusts/i);assert.ok(getScenarioCopy(Scenario.CHOKING,AgeGroup.CHILD));assert.ok(getScenarioCopy(Scenario.CHOKING,AgeGroup.INFANT));});
test('stroke guidance implements FAST and call 999 even if symptoms stop',()=>{const t=getScenarioCopy(Scenario.STROKE).steps.join(' ');assert.match(t,/FACE:/);assert.match(t,/ARMS:/);assert.match(t,/SPEECH:/);assert.match(t,/call 999 immediately/i);assert.match(t,/even if symptoms have stopped/i);});
test('anaphylaxis guidance prioritises adrenaline and 999 with second injector after 5 minutes',()=>{const t=getScenarioCopy(Scenario.ANAPHYLAXIS).steps.join(' ');assert.match(t,/auto-injector immediately/i);assert.match(t,/Call 999/i);assert.match(t,/after 5 minutes/i);});
test('severe bleeding guidance includes direct pressure and tourniquet escalation',()=>{const t=getScenarioCopy(Scenario.SEVERE_BLEEDING).steps.join(' ');assert.match(t,/direct manual pressure/i);assert.match(t,/5–7 cm above/i);assert.match(t,/do not release/i);});

test('fall/head/spine guidance minimises movement and prioritises airway',()=>{const t=getScenarioCopy(Scenario.FALL_HEAD_SPINE).steps.join(' ');assert.match(t,/call 999/i);assert.match(t,/Do not move/i);assert.match(t,/airway/i);assert.match(t,/priority/i);});
test('crush injury guidance starts with hazard isolation and emergency escalation',()=>{const t=getScenarioCopy(Scenario.CRUSH_INJURY).steps.join(' ');assert.match(t,/isolated/i);assert.match(t,/Call 999/i);assert.match(t,/Do not attempt a dangerous release/i);assert.match(t,/spine movement/i);});
test('electrical injury guidance prevents contact until power is isolated and covers CPR/AED',()=>{const t=getScenarioCopy(Scenario.ELECTRICAL_INJURY).steps.join(' ');assert.match(t,/Do not touch/i);assert.match(t,/Isolate the supply/i);assert.match(t,/Call 999/i);assert.match(t,/CPR/i);assert.match(t,/AED/i);assert.match(t,/20 minutes/i);});
test('serious thermal burn guidance cools for 20 minutes and avoids ice or creams',()=>{const t=getScenarioCopy(Scenario.THERMAL_BURN).steps.join(' ');assert.match(t,/20 minutes/i);assert.match(t,/cool or lukewarm running water/i);assert.match(t,/Do not use ice/i);assert.match(t,/Call 999/i);});
test('chemical burn guidance calls 999 and irrigates for about one hour without neutralising',()=>{const t=getScenarioCopy(Scenario.CHEMICAL_BURN).steps.join(' ');assert.match(t,/Call 999/i);assert.match(t,/about 1 hour/i);assert.match(t,/Do not apply creams/i);assert.match(t,/neutralise/i);});
test('amputation guidance controls bleeding first and preserves part cold without freezing',()=>{const t=getScenarioCopy(Scenario.AMPUTATION).steps.join(' ');assert.match(t,/control life-threatening bleeding first/i);assert.match(t,/watertight bag/i);assert.match(t,/ice or ice water/i);assert.match(t,/Do not let the body part touch ice directly/i);assert.match(t,/same hospital/i);});

test('all construction trauma scenarios route from picker to guidance',()=>{for(const scenario of [Scenario.FALL_HEAD_SPINE,Scenario.CRUSH_INJURY,Scenario.ELECTRICAL_INJURY,Scenario.THERMAL_BURN,Scenario.CHEMICAL_BURN,Scenario.AMPUTATION]){let s=answerFlow(Answer.YES,Answer.YES,Answer.NO);s=reduceIncident(s,{type:'SELECT_SCENARIO',scenario});assert.equal(s.state,IncidentState.GUIDANCE);assert.equal(s.scenario,scenario);assert.ok(getScenarioCopy(scenario)?.steps?.length>=4);}});

test('dialler state never claims connection or dispatch',()=>{let s=createIncident();s=reduceIncident(s,{type:'CALL_DIALER_OPENED',number:'999'});assert.equal(s.callState,'DIALER_OPENED_CONNECTION_UNKNOWN');assert.equal(s.callNumber,'999');});
test('production HTML has original Emergency Core visual structure and no fake responder UI',async()=>{const h=await readFile(new URL('../index.html',import.meta.url),'utf8');for(const token of ['start-screen','activate-button','emergency-shell','status-grid','decision-panel'])assert.match(h,new RegExp(token));for(const pattern of [/ALERTING DEMO/i,/SYNTHETIC/i,/RESPONDER VIEW/i,/JOIN LIVE AUDIO/i,/DEMO SITE/i])assert.doesNotMatch(h,pattern);});
test('construction runtime contains trauma choices and no child or baby selector UI',async()=>{const app=await readFile(new URL('../src/app.js',import.meta.url),'utf8');for(const label of ['FALL / HEAD / SPINE','CRUSH / ENTRAPMENT','ELECTRICAL','SERIOUS BURN','CHEMICAL BURN','AMPUTATION'])assert.match(app,new RegExp(label.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.doesNotMatch(app,/data-age=|>CHILD<|>BABY</i);});
test('runtime contains no fake responder simulation or backend transport',async()=>{const app=await readFile(new URL('../src/app.js',import.meta.url),'utf8');const state=await readFile(new URL('../src/emergency-state.js',import.meta.url),'utf8');const source=app+state;for(const p of [/demo-first-aider/i,/responderTimers/i,/WebSocket/i,/XMLHttpRequest/i,/EventSource/i,/MediaRecorder/i,/fetch\s*\(/])assert.doesNotMatch(source,p);});
test('999/112 opens device dialler truthfully',async()=>{const app=await readFile(new URL('../src/app.js',import.meta.url),'utf8');assert.match(app,/window\.location\.href=`tel:\$\{number\}`/);assert.match(app,/CONNECTION NOT CONFIRMED/);assert.doesNotMatch(app,/ambulance dispatched|call connected|services notified/i);});
test('offline worker caches core UI and new engine layer',async()=>{const sw=await readFile(new URL('../service-worker.js',import.meta.url),'utf8');for(const f of ['index.html','styles.css','engine.css','app.webmanifest','src/app.js','src/emergency-state.js','icons/icon-192.png','icons/icon-512.png'])assert.match(sw,new RegExp(f.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(sw,/caches\.open/);assert.match(sw,/caches\.match/);});
test('industrial Emergency Core CSS remains baseline and engine additions do not replace it',async()=>{const h=await readFile(new URL('../index.html',import.meta.url),'utf8');const e=await readFile(new URL('../engine.css',import.meta.url),'utf8');assert.match(h,/href="styles\.css"/);assert.match(h,/href="engine\.css"/);assert.match(e,/original Emergency Core visual system remains in styles\.css/i);});
