import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import { AgeGroup, Answer, IncidentState, Scenario, createIncident, getScenarioCopy, reduceIncident } from '../src/emergency-state.js';

function answerFlow(...answers){ let s=createIncident('2026-09-05T00:00:00Z'); for(const a of answers)s=reduceIncident(s,{type:'ANSWER',answer:a}); return s; }

test('scene unsafe immediately gives safety guidance',()=>{const s=answerFlow(Answer.NO);assert.equal(s.state,IncidentState.GUIDANCE);assert.equal(s.scenario,Scenario.SCENE_UNSAFE);});
test('unresponsive and not breathing routes to CPR age selection',()=>{const s=answerFlow(Answer.YES,Answer.NO,Answer.NO);assert.equal(s.state,IncidentState.AGE_SELECT);assert.equal(s.scenario,Scenario.CPR);});
test('unresponsive but breathing routes to unconscious-breathing guidance',()=>{const s=answerFlow(Answer.YES,Answer.NO,Answer.YES);assert.equal(s.scenario,Scenario.UNCONSCIOUS_BREATHING);assert.equal(s.state,IncidentState.GUIDANCE);});
test('responsive severe bleeding routes directly to bleeding control',()=>{const s=answerFlow(Answer.YES,Answer.YES,Answer.YES);assert.equal(s.scenario,Scenario.SEVERE_BLEEDING);assert.equal(s.state,IncidentState.GUIDANCE);});
test('responsive without severe bleeding opens scenario picker',()=>{const s=answerFlow(Answer.YES,Answer.YES,Answer.NO);assert.equal(s.state,IncidentState.SCENARIO_PICKER);});
test('CPR requires age and has distinct adult child infant protocols',()=>{for(const age of Object.values(AgeGroup)){let s=answerFlow(Answer.YES,Answer.YES,Answer.NO);s=reduceIncident(s,{type:'SELECT_SCENARIO',scenario:Scenario.CPR});assert.equal(s.state,IncidentState.AGE_SELECT);s=reduceIncident(s,{type:'SELECT_AGE',ageGroup:age});assert.equal(s.state,IncidentState.GUIDANCE);const g=getScenarioCopy(Scenario.CPR,age);assert.ok(g.rhythm);assert.ok(g.steps.length>=5);}assert.match(getScenarioCopy(Scenario.CPR,AgeGroup.ADULT).steps.join(' '),/5–6 cm/);assert.match(getScenarioCopy(Scenario.CPR,AgeGroup.CHILD).steps.join(' '),/5 initial rescue breaths/);assert.match(getScenarioCopy(Scenario.CPR,AgeGroup.INFANT).steps.join(' '),/4 cm/);});
test('choking has adult child and infant-specific technique',()=>{assert.match(getScenarioCopy(Scenario.CHOKING,AgeGroup.ADULT).steps.join(' '),/abdominal thrusts/i);assert.match(getScenarioCopy(Scenario.CHOKING,AgeGroup.CHILD).steps.join(' '),/abdominal thrusts/i);assert.match(getScenarioCopy(Scenario.CHOKING,AgeGroup.INFANT).steps.join(' '),/Do not use abdominal thrusts/i);assert.match(getScenarioCopy(Scenario.CHOKING,AgeGroup.INFANT).steps.join(' '),/chest thrusts/i);});
test('stroke guidance implements FAST and call 999 even if symptoms stop',()=>{const t=getScenarioCopy(Scenario.STROKE).steps.join(' ');assert.match(t,/FACE:/);assert.match(t,/ARMS:/);assert.match(t,/SPEECH:/);assert.match(t,/call 999 immediately/i);assert.match(t,/even if symptoms have stopped/i);});
test('anaphylaxis guidance prioritises adrenaline and 999 with second injector after 5 minutes',()=>{const t=getScenarioCopy(Scenario.ANAPHYLAXIS).steps.join(' ');assert.match(t,/auto-injector immediately/i);assert.match(t,/Call 999/i);assert.match(t,/after 5 minutes/i);});
test('severe bleeding guidance includes direct pressure and tourniquet escalation',()=>{const t=getScenarioCopy(Scenario.SEVERE_BLEEDING).steps.join(' ');assert.match(t,/direct manual pressure/i);assert.match(t,/5–7 cm above/i);assert.match(t,/do not release/i);});
test('dialler state never claims connection or dispatch',()=>{let s=createIncident();s=reduceIncident(s,{type:'CALL_DIALER_OPENED',number:'999'});assert.equal(s.callState,'DIALER_OPENED_CONNECTION_UNKNOWN');assert.equal(s.callNumber,'999');});
test('production HTML has original Emergency Core visual structure and no fake responder UI',async()=>{const h=await readFile(new URL('../index.html',import.meta.url),'utf8');for(const token of ['start-screen','activate-button','emergency-shell','status-grid','decision-panel'])assert.match(h,new RegExp(token));for(const pattern of [/ALERTING DEMO/i,/SYNTHETIC/i,/RESPONDER VIEW/i,/JOIN LIVE AUDIO/i,/DEMO SITE/i])assert.doesNotMatch(h,pattern);});
test('runtime contains no fake responder simulation or backend transport',async()=>{const app=await readFile(new URL('../src/app.js',import.meta.url),'utf8');const state=await readFile(new URL('../src/emergency-state.js',import.meta.url),'utf8');const source=app+state;for(const p of [/demo-first-aider/i,/responderTimers/i,/WebSocket/i,/XMLHttpRequest/i,/EventSource/i,/MediaRecorder/i,/fetch\s*\(/])assert.doesNotMatch(source,p);});
test('999/112 opens device dialler truthfully',async()=>{const app=await readFile(new URL('../src/app.js',import.meta.url),'utf8');assert.match(app,/window\.location\.href=`tel:\$\{number\}`/);assert.match(app,/CONNECTION NOT CONFIRMED/);assert.doesNotMatch(app,/ambulance dispatched|call connected|services notified/i);});
test('offline worker caches core UI and new engine layer',async()=>{const sw=await readFile(new URL('../service-worker.js',import.meta.url),'utf8');for(const f of ['index.html','styles.css','engine.css','app.webmanifest','src/app.js','src/emergency-state.js','icons/icon-192.png','icons/icon-512.png'])assert.match(sw,new RegExp(f.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(sw,/caches\.open/);assert.match(sw,/caches\.match/);});
test('industrial Emergency Core CSS remains baseline and engine additions do not replace it',async()=>{const h=await readFile(new URL('../index.html',import.meta.url),'utf8');const e=await readFile(new URL('../engine.css',import.meta.url),'utf8');assert.match(h,/href="styles\.css"/);assert.match(h,/href="engine\.css"/);assert.match(e,/original Emergency Core visual system remains in styles\.css/i);});
